language: python

# this is needed to run tests requiring a graphical user interface
# see https://docs.travis-ci.com/user/gui-and-headless-browsers/
dist: xenial
services:
  - xvfb

python:
  - "3.7"

install: 

  # setup conda, which is necessary to install qutip
  # just copied in the conda code from https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html#
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # Here we also install all dependencies of qucat
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib sympy pillow nbformat pytest
  - source activate test-environment
  
  # Install qutip
  - conda config --append channels conda-forge
  - conda install qutip

script: 
  - pytest